<?php /** @noinspection AutoloadingIssuesInspection *//** @noinspection PhpUnused */

namespace Pyro\IdeHelper\Examples;

class PermissionsExamples
{
    public static function permissions()
    {
        return [
        'streams::maintenance.access',
'streams::control_panel.access',
'streams::control_panel.sidebar',
'anomaly.module.settings::settings.write',
'anomaly.module.preferences::preferences.write',
'anomaly.module.blocks::areas.read',
'anomaly.module.blocks::areas.write',
'anomaly.module.blocks::areas.delete',
'anomaly.module.blocks::blocks.read',
'anomaly.module.blocks::blocks.write',
'anomaly.module.blocks::blocks.delete',
'anomaly.module.dashboard::dashboards.read',
'anomaly.module.dashboard::dashboards.write',
'anomaly.module.dashboard::dashboards.delete',
'anomaly.module.dashboard::widgets.read',
'anomaly.module.dashboard::widgets.write',
'anomaly.module.dashboard::widgets.delete',
'anomaly.module.files::files.read',
'anomaly.module.files::files.write',
'anomaly.module.files::files.delete',
'anomaly.module.files::folders.read',
'anomaly.module.files::folders.write',
'anomaly.module.files::folders.delete',
'anomaly.module.files::disks.read',
'anomaly.module.files::disks.write',
'anomaly.module.files::disks.delete',
'anomaly.module.files::fields.manage',
'anomaly.module.grids::grids.read',
'anomaly.module.grids::grids.write',
'anomaly.module.grids::grids.delete',
'anomaly.module.grids::grids.fields',
'anomaly.module.grids::fields.manage',
'anomaly.module.navigation::menus.read',
'anomaly.module.navigation::menus.write',
'anomaly.module.navigation::menus.delete',
'anomaly.module.navigation::links.read',
'anomaly.module.navigation::links.write',
'anomaly.module.navigation::links.delete',
'anomaly.module.pages::pages.read',
            'anomaly.module.pages::pages.write',
            'anomaly.module.pages::pages.delete',
            'anomaly.module.pages::pages.preview',
            'anomaly.module.pages::types.read',
            'anomaly.module.pages::types.write',
            'anomaly.module.pages::types.delete',
            'anomaly.module.pages::types.fields',
            'anomaly.module.pages::fields.manage',
            'anomaly.module.redirects::redirects.read',
            'anomaly.module.redirects::redirects.write',
            'anomaly.module.redirects::redirects.delete',
            'anomaly.module.redirects::domains.read',
            'anomaly.module.redirects::domains.write',
            'anomaly.module.redirects::domains.delete',
            'anomaly.module.repeaters::repeaters.read',
            'anomaly.module.repeaters::repeaters.write',
            'anomaly.module.repeaters::repeaters.delete',
            'anomaly.module.repeaters::repeaters.fields',
            'anomaly.module.repeaters::fields.manage',
            'anomaly.module.search::items.read',
            'anomaly.module.search::items.write',
            'anomaly.module.search::items.delete',
            'anomaly.module.users::users.read',
            'anomaly.module.users::users.write',
            'anomaly.module.users::users.write_admins',
            'anomaly.module.users::users.impersonate',
            'anomaly.module.users::users.delete',
            'anomaly.module.users::users.manage_permissions',
            'anomaly.module.users::roles.read',
            'anomaly.module.users::roles.write',
            'anomaly.module.users::roles.delete',
            'anomaly.module.users::fields.manage',
            'anomaly.module.users::settings.manage',
            'crvs.module.activities::activity.read',
            'crvs.module.activities::activity.write',
            'crvs.module.activities::activity.delete',
            'crvs.extension.care_role_type::intake.read',
            'crvs.extension.care_role_type::intake.write',
            'crvs.extension.care_role_type::intake.delete',
            'crvs.extension.caretaker_role_type::intake.read',
            'crvs.extension.caretaker_role_type::intake.write',
            'crvs.extension.caretaker_role_type::intake.delete',
            'crvs.extension.caretaker_role_type::intake_caregivers.read',
            'crvs.extension.caretaker_role_type::intake_caregivers.write',
            'crvs.extension.caretaker_role_type::intake_caregivers.delete',
            'crvs.extension.caretaker_role_type::intake_restriction.read',
            'crvs.extension.caretaker_role_type::intake_restriction.write',
            'crvs.extension.caretaker_role_type::intake_restriction.delete',
            'crvs.extension.caretaker_role_type::intake_provided_care.read',
            'crvs.extension.caretaker_role_type::intake_provided_care.write',
            'crvs.extension.caretaker_role_type::intake_provided_care.delete',
            'crvs.extension.caretaker_role_type::intake_overpressures.read',
            'crvs.extension.caretaker_role_type::intake_overpressures.write',
            'crvs.extension.caretaker_role_type::intake_overpressures.delete',
            'crvs.extension.caretaker_role_type::intake_restrictions.read',
            'crvs.extension.caretaker_role_type::intake_restrictions.write',
            'crvs.extension.caretaker_role_type::intake_restrictions.delete',
            'crvs.extension.caretaker_role_type::intake_hours.read',
            'crvs.extension.caretaker_role_type::intake_hours.write',
            'crvs.extension.caretaker_role_type::intake_hours.delete',
            'crvs.module.ci::projects.read',
            'crvs.module.ci::projects.write',
            'crvs.module.ci::projects.delete',
            'crvs.module.ci::hosts.read',
            'crvs.module.ci::hosts.write',
            'crvs.module.ci::hosts.delete',
            'crvs.module.ci::servers.read',
            'crvs.module.ci::servers.write',
            'crvs.module.ci::servers.delete',
            'crvs.module.client_registrations::reports.read',
            'crvs.module.client_registrations::reports.write',
            'crvs.module.client_registrations::reports.delete',
            'crvs.module.client_registrations::categories.read',
            'crvs.module.client_registrations::categories.write',
            'crvs.module.client_registrations::categories.delete',
            'crvs.module.client_registrations::subjects.read',
            'crvs.module.client_registrations::subjects.write',
            'crvs.module.client_registrations::subjects.delete',
            'crvs.module.client_registrations::registrations.read',
            'crvs.module.client_registrations::registrations.write',
            'crvs.module.client_registrations::registrations.delete',
            'crvs.module.client_registrations::actions.read',
            'crvs.module.client_registrations::actions.write',
            'crvs.module.client_registrations::actions.delete',
            'crvs.module.clients::clients.read',
            'crvs.module.clients::clients.write',
            'crvs.module.clients::clients.delete',
            'crvs.module.clients::fields.read',
            'crvs.module.clients::fields.write',
            'crvs.module.clients::fields.delete',
            'crvs.module.clients::roles.read',
            'crvs.module.clients::roles.write',
            'crvs.module.clients::roles.delete',
            'crvs.module.clients::documents.read',
            'crvs.module.clients::documents.write',
            'crvs.module.clients::documents.delete',
            'crvs.module.clients::client_role_advisors.read',
            'crvs.module.clients::client_role_advisors.write',
            'crvs.module.clients::client_role_advisors.delete',
            'crvs.module.clients::client_role_department.read',
            'crvs.module.clients::client_role_department.write',
            'crvs.module.clients::client_role_department.delete',
            'crvs.module.clients::advisor.read',
            'crvs.module.clients::advisor.write',
            'crvs.module.clients::advisor.delete',
            'crvs.module.clients::advisors.read',
            'crvs.module.clients::advisors.write',
            'crvs.module.clients::advisors.delete',
            'crvs.module.clients::client_roles.read',
            'crvs.module.clients::client_roles.write',
            'crvs.module.clients::client_roles.delete',
            'crvs.module.clients::groups.read',
            'crvs.module.clients::groups.write',
            'crvs.module.clients::groups.delete',
            'crvs.module.clients::registrations.read',
            'crvs.module.clients::registrations.write',
            'crvs.module.clients::registrations.delete',
            'crvs.module.clients::create_registrations_fields.read',
            'crvs.module.clients::create_registrations_fields.write',
            'crvs.module.clients::create_registrations_fields.delete',
            'crvs.module.clients::reports.read',
            'crvs.module.clients::reports.write',
            'crvs.module.clients::reports.delete',
            'crvs.module.clients::instances.read',
            'crvs.module.clients::instances.write',
            'crvs.module.clients::instances.delete',
            'crvs.module.clients::dossiers.read',
            'crvs.module.clients::dossiers.write',
            'crvs.module.clients::dossiers.delete',
            'crvs.module.clients::client-advisor.read',
            'crvs.module.clients::client-advisor.write',
            'crvs.module.clients::client-advisor.delete',
            'crvs.module.clients::client_advisor.read',
            'crvs.module.clients::client_advisor.write',
            'crvs.module.clients::client_advisor.delete',
            'crvs.module.contacts::contacts.read',
            'crvs.module.contacts::contacts.write',
            'crvs.module.contacts::contacts.delete',
            'crvs.module.core::instances.read',
            'crvs.module.core::instances.write',
            'crvs.module.core::instances.delete',
            'crvs.module.core::education_levels.read',
            'crvs.module.core::education_levels.write',
            'crvs.module.core::education_levels.delete',
            'crvs.module.core::layout.sidebar',
            'crvs.extension.courses_role_type::intake.read',
            'crvs.extension.courses_role_type::intake.write',
            'crvs.extension.courses_role_type::intake.delete',
            'crvs.module.departments::user.select',
            'crvs.module.departments::user.deselect',
            'crvs.module.departments::user.all_departments',
            'crvs.module.departments::user.select_disabled',
            'crvs.module.departments::department.read',
            'crvs.module.departments::department.write',
            'crvs.module.departments::department.delete',
            'crvs.module.departments::department.enable',
            'crvs.module.departments::department.disable',
            'crvs.module.departments::associations.read',
            'crvs.module.departments::associations.write',
            'crvs.module.departments::associations.delete',
            'crvs.module.departments::linked_streams.form_edit_department',
            'crvs.module.departments::linked_streams.show_all_entries',
            'crvs.module.departments::settings.edit',
            'crvs.module.faq::Categories.read',
            'crvs.module.faq::Categories.write',
            'crvs.module.faq::Categories.delete',
            'crvs.module.faq::Questions.read',
            'crvs.module.faq::Questions.write',
            'crvs.module.faq::Questions.delete',
            'crvs.module.files::files.read',
            'crvs.module.files::files.write',
            'crvs.module.files::files.delete',
            'crvs.module.files::folders.read',
            'crvs.module.files::folders.write',
            'crvs.module.files::folders.delete',
            'crvs.module.files::disks.read',
            'crvs.module.files::disks.write',
            'crvs.module.files::disks.delete',
            'crvs.module.files::fields.manage',
            'crvs.module.notes::notes.read',
            'crvs.module.notes::notes.write',
            'crvs.module.notes::notes.delete',
            'crvs.extension.requester_role_type::requests.read',
            'crvs.extension.requester_role_type::requests.write',
            'crvs.extension.requester_role_type::requests.delete',
            'crvs.extension.requester_role_type::requests.match',
            'crvs.extension.requester_role_type::request_categories.read',
            'crvs.extension.requester_role_type::request_categories.write',
            'crvs.extension.requester_role_type::request_categories.delete',
            'crvs.extension.requester_role_type::intake.read',
            'crvs.extension.requester_role_type::intake.write',
            'crvs.extension.requester_role_type::intake.delete',
            'crvs.extension.requester_role_type::instances.read',
            'crvs.extension.requester_role_type::instances.write',
            'crvs.extension.requester_role_type::instances.delete',
            'crvs.extension.requester_role_type::groups.read',
            'crvs.extension.requester_role_type::groups.write',
            'crvs.extension.requester_role_type::groups.delete',
            'crvs.extension.requester_role_type::categories.read',
            'crvs.extension.requester_role_type::categories.write',
            'crvs.extension.requester_role_type::categories.delete',
            'crvs.extension.requester_role_type::matches.read',
            'crvs.extension.requester_role_type::matches.write',
            'crvs.extension.requester_role_type::matches.delete',
            'crvs.extension.requester_role_type::reason_closed.read',
            'crvs.extension.requester_role_type::reason_closed.write',
            'crvs.extension.requester_role_type::reason_closed.delete',
            'crvs.extension.requester_role_type::reason_unfilled.read',
            'crvs.extension.requester_role_type::reason_unfilled.write',
            'crvs.extension.requester_role_type::reason_unfilled.delete',
            'crvs.extension.requester_role_type::caretakers.read',
            'crvs.extension.requester_role_type::caretakers.write',
            'crvs.extension.requester_role_type::caretakers.delete',
            'crvs.extension.volunteer_role_type::intake.read',
            'crvs.extension.volunteer_role_type::intake.write',
            'crvs.extension.volunteer_role_type::intake.delete',
            'examples.module.ex1::departments.read',
            'examples.module.ex1::departments.write',
            'examples.module.ex1::departments.delete',
            'pyro.module.activity_log::activity.read',
            'pyro.module.activity_log::activity.write',
            'pyro.module.activity_log::activity.delete',
            'pyro.module.menus::menus.read',
            'pyro.module.menus::menus.write',
            'pyro.module.menus::menus.delete',
            'pyro.module.menus::links.read',
            'pyro.module.menus::links.write',
            'pyro.module.menus::links.delete',
            'pyro.module.news::items.read',
            'pyro.module.news::items.write',
            'pyro.module.news::items.delete',
            'pyro.module.reactable::action.read',
            'pyro.module.reactable::action.write',
            'pyro.module.reactable::action.delete',
            'pyro.module.reactable::triggers.read',
            'pyro.module.reactable::triggers.write',
            'pyro.module.reactable::triggers.delete',
            'pyro.module.reactable::actions.read',
            'pyro.module.reactable::actions.write',
            'pyro.module.reactable::actions.delete',
            'pyro.module.reactable::trigger.read',
            'pyro.module.reactable::trigger.write',
            'pyro.module.reactable::trigger.delete',
        ];
    }

    public static function permissionsAssoc()
    {
        return [
            'streams::maintenance.access'                                     => 'streams::maintenance.access',
            'streams::control_panel.access'                                   => 'streams::control_panel.access',
            'streams::control_panel.sidebar'                                  => 'streams::control_panel.sidebar',
            'anomaly.module.settings::settings.write'                         => 'anomaly.module.settings::settings.write',
            'anomaly.module.preferences::preferences.write'                   => 'anomaly.module.preferences::preferences.write',
            'anomaly.module.blocks::areas.read'                               => 'anomaly.module.blocks::areas.read',
            'anomaly.module.blocks::areas.write'                              => 'anomaly.module.blocks::areas.write',
            'anomaly.module.blocks::areas.delete'                             => 'anomaly.module.blocks::areas.delete',
            'anomaly.module.blocks::blocks.read'                              => 'anomaly.module.blocks::blocks.read',
            'anomaly.module.blocks::blocks.write'                             => 'anomaly.module.blocks::blocks.write',
            'anomaly.module.blocks::blocks.delete'                            => 'anomaly.module.blocks::blocks.delete',
            'anomaly.module.dashboard::dashboards.read'                       => 'anomaly.module.dashboard::dashboards.read',
            'anomaly.module.dashboard::dashboards.write'                      => 'anomaly.module.dashboard::dashboards.write',
            'anomaly.module.dashboard::dashboards.delete'                     => 'anomaly.module.dashboard::dashboards.delete',
            'anomaly.module.dashboard::widgets.read'                          => 'anomaly.module.dashboard::widgets.read',
            'anomaly.module.dashboard::widgets.write'                         => 'anomaly.module.dashboard::widgets.write',
            'anomaly.module.dashboard::widgets.delete'                        => 'anomaly.module.dashboard::widgets.delete',
            'anomaly.module.files::files.read'                                => 'anomaly.module.files::files.read',
            'anomaly.module.files::files.write'                               => 'anomaly.module.files::files.write',
            'anomaly.module.files::files.delete'                              => 'anomaly.module.files::files.delete',
            'anomaly.module.files::folders.read'                              => 'anomaly.module.files::folders.read',
            'anomaly.module.files::folders.write'                             => 'anomaly.module.files::folders.write',
            'anomaly.module.files::folders.delete'                            => 'anomaly.module.files::folders.delete',
            'anomaly.module.files::disks.read'                                => 'anomaly.module.files::disks.read',
            'anomaly.module.files::disks.write'                               => 'anomaly.module.files::disks.write',
            'anomaly.module.files::disks.delete'                              => 'anomaly.module.files::disks.delete',
            'anomaly.module.files::fields.manage'                             => 'anomaly.module.files::fields.manage',
            'anomaly.module.grids::grids.read'                                => 'anomaly.module.grids::grids.read',
            'anomaly.module.grids::grids.write'                               => 'anomaly.module.grids::grids.write',
            'anomaly.module.grids::grids.delete'                              => 'anomaly.module.grids::grids.delete',
            'anomaly.module.grids::grids.fields'                              => 'anomaly.module.grids::grids.fields',
            'anomaly.module.grids::fields.manage'                             => 'anomaly.module.grids::fields.manage',
            'anomaly.module.navigation::menus.read'                           => 'anomaly.module.navigation::menus.read',
            'anomaly.module.navigation::menus.write'                          => 'anomaly.module.navigation::menus.write',
            'anomaly.module.navigation::menus.delete'                         => 'anomaly.module.navigation::menus.delete',
            'anomaly.module.navigation::links.read'                           => 'anomaly.module.navigation::links.read',
            'anomaly.module.navigation::links.write'                          => 'anomaly.module.navigation::links.write',
            'anomaly.module.navigation::links.delete'                         => 'anomaly.module.navigation::links.delete',
            'anomaly.module.pages::pages.read'                                => 'anomaly.module.pages::pages.read',
            'anomaly.module.pages::pages.write'                               => 'anomaly.module.pages::pages.write',
            'anomaly.module.pages::pages.delete'                              => 'anomaly.module.pages::pages.delete',
            'anomaly.module.pages::pages.preview'                             => 'anomaly.module.pages::pages.preview',
            'anomaly.module.pages::types.read'                                => 'anomaly.module.pages::types.read',
            'anomaly.module.pages::types.write'                               => 'anomaly.module.pages::types.write',
            'anomaly.module.pages::types.delete'                              => 'anomaly.module.pages::types.delete',
            'anomaly.module.pages::types.fields'                              => 'anomaly.module.pages::types.fields',
            'anomaly.module.pages::fields.manage'                             => 'anomaly.module.pages::fields.manage',
            'anomaly.module.redirects::redirects.read'                        => 'anomaly.module.redirects::redirects.read',
            'anomaly.module.redirects::redirects.write'                       => 'anomaly.module.redirects::redirects.write',
            'anomaly.module.redirects::redirects.delete'                      => 'anomaly.module.redirects::redirects.delete',
            'anomaly.module.redirects::domains.read'                          => 'anomaly.module.redirects::domains.read',
            'anomaly.module.redirects::domains.write'                         => 'anomaly.module.redirects::domains.write',
            'anomaly.module.redirects::domains.delete'                        => 'anomaly.module.redirects::domains.delete',
            'anomaly.module.repeaters::repeaters.read'                        => 'anomaly.module.repeaters::repeaters.read',
            'anomaly.module.repeaters::repeaters.write'                       => 'anomaly.module.repeaters::repeaters.write',
            'anomaly.module.repeaters::repeaters.delete'                      => 'anomaly.module.repeaters::repeaters.delete',
            'anomaly.module.repeaters::repeaters.fields'                      => 'anomaly.module.repeaters::repeaters.fields',
            'anomaly.module.repeaters::fields.manage'                         => 'anomaly.module.repeaters::fields.manage',
            'anomaly.module.search::items.read'                               => 'anomaly.module.search::items.read',
            'anomaly.module.search::items.write'                              => 'anomaly.module.search::items.write',
            'anomaly.module.search::items.delete'                             => 'anomaly.module.search::items.delete',
            'anomaly.module.users::users.read'                                => 'anomaly.module.users::users.read',
            'anomaly.module.users::users.write'                               => 'anomaly.module.users::users.write',
            'anomaly.module.users::users.write_admins'                        => 'anomaly.module.users::users.write_admins',
            'anomaly.module.users::users.impersonate'                         => 'anomaly.module.users::users.impersonate',
            'anomaly.module.users::users.delete'                              => 'anomaly.module.users::users.delete',
            'anomaly.module.users::users.manage_permissions'                  => 'anomaly.module.users::users.manage_permissions',
            'anomaly.module.users::roles.read'                                => 'anomaly.module.users::roles.read',
            'anomaly.module.users::roles.write'                               => 'anomaly.module.users::roles.write',
            'anomaly.module.users::roles.delete'                              => 'anomaly.module.users::roles.delete',
            'anomaly.module.users::fields.manage'                             => 'anomaly.module.users::fields.manage',
            'anomaly.module.users::settings.manage'                           => 'anomaly.module.users::settings.manage',
            'crvs.module.activities::activity.read'                           => 'crvs.module.activities::activity.read',
            'crvs.module.activities::activity.write'                          => 'crvs.module.activities::activity.write',
            'crvs.module.activities::activity.delete'                         => 'crvs.module.activities::activity.delete',
            'crvs.extension.care_role_type::intake.read'                      => 'crvs.extension.care_role_type::intake.read',
            'crvs.extension.care_role_type::intake.write'                     => 'crvs.extension.care_role_type::intake.write',
            'crvs.extension.care_role_type::intake.delete'                    => 'crvs.extension.care_role_type::intake.delete',
            'crvs.extension.caretaker_role_type::intake.read'                 => 'crvs.extension.caretaker_role_type::intake.read',
            'crvs.extension.caretaker_role_type::intake.write'                => 'crvs.extension.caretaker_role_type::intake.write',
            'crvs.extension.caretaker_role_type::intake.delete'               => 'crvs.extension.caretaker_role_type::intake.delete',
            'crvs.extension.caretaker_role_type::intake_caregivers.read'      => 'crvs.extension.caretaker_role_type::intake_caregivers.read',
            'crvs.extension.caretaker_role_type::intake_caregivers.write'     => 'crvs.extension.caretaker_role_type::intake_caregivers.write',
            'crvs.extension.caretaker_role_type::intake_caregivers.delete'    => 'crvs.extension.caretaker_role_type::intake_caregivers.delete',
            'crvs.extension.caretaker_role_type::intake_restriction.read'     => 'crvs.extension.caretaker_role_type::intake_restriction.read',
            'crvs.extension.caretaker_role_type::intake_restriction.write'    => 'crvs.extension.caretaker_role_type::intake_restriction.write',
            'crvs.extension.caretaker_role_type::intake_restriction.delete'   => 'crvs.extension.caretaker_role_type::intake_restriction.delete',
            'crvs.extension.caretaker_role_type::intake_provided_care.read'   => 'crvs.extension.caretaker_role_type::intake_provided_care.read',
            'crvs.extension.caretaker_role_type::intake_provided_care.write'  => 'crvs.extension.caretaker_role_type::intake_provided_care.write',
            'crvs.extension.caretaker_role_type::intake_provided_care.delete' => 'crvs.extension.caretaker_role_type::intake_provided_care.delete',
            'crvs.extension.caretaker_role_type::intake_overpressures.read'   => 'crvs.extension.caretaker_role_type::intake_overpressures.read',
            'crvs.extension.caretaker_role_type::intake_overpressures.write'  => 'crvs.extension.caretaker_role_type::intake_overpressures.write',
            'crvs.extension.caretaker_role_type::intake_overpressures.delete' => 'crvs.extension.caretaker_role_type::intake_overpressures.delete',
            'crvs.extension.caretaker_role_type::intake_restrictions.read'    => 'crvs.extension.caretaker_role_type::intake_restrictions.read',
            'crvs.extension.caretaker_role_type::intake_restrictions.write'   => 'crvs.extension.caretaker_role_type::intake_restrictions.write',
            'crvs.extension.caretaker_role_type::intake_restrictions.delete'  => 'crvs.extension.caretaker_role_type::intake_restrictions.delete',
            'crvs.extension.caretaker_role_type::intake_hours.read'           => 'crvs.extension.caretaker_role_type::intake_hours.read',
            'crvs.extension.caretaker_role_type::intake_hours.write'          => 'crvs.extension.caretaker_role_type::intake_hours.write',
            'crvs.extension.caretaker_role_type::intake_hours.delete'         => 'crvs.extension.caretaker_role_type::intake_hours.delete',
            'crvs.module.ci::projects.read'                                   => 'crvs.module.ci::projects.read',
            'crvs.module.ci::projects.write'                                  => 'crvs.module.ci::projects.write',
            'crvs.module.ci::projects.delete'                                 => 'crvs.module.ci::projects.delete',
            'crvs.module.ci::hosts.read'                                      => 'crvs.module.ci::hosts.read',
            'crvs.module.ci::hosts.write'                                     => 'crvs.module.ci::hosts.write',
            'crvs.module.ci::hosts.delete'                                    => 'crvs.module.ci::hosts.delete',
            'crvs.module.ci::servers.read'                                    => 'crvs.module.ci::servers.read',
            'crvs.module.ci::servers.write'                                   => 'crvs.module.ci::servers.write',
            'crvs.module.ci::servers.delete'                                  => 'crvs.module.ci::servers.delete',
            'crvs.module.client_registrations::reports.read'                  => 'crvs.module.client_registrations::reports.read',
            'crvs.module.client_registrations::reports.write'                 => 'crvs.module.client_registrations::reports.write',
            'crvs.module.client_registrations::reports.delete'                => 'crvs.module.client_registrations::reports.delete',
            'crvs.module.client_registrations::categories.read'               => 'crvs.module.client_registrations::categories.read',
            'crvs.module.client_registrations::categories.write'              => 'crvs.module.client_registrations::categories.write',
            'crvs.module.client_registrations::categories.delete'             => 'crvs.module.client_registrations::categories.delete',
            'crvs.module.client_registrations::subjects.read'                 => 'crvs.module.client_registrations::subjects.read',
            'crvs.module.client_registrations::subjects.write'                => 'crvs.module.client_registrations::subjects.write',
            'crvs.module.client_registrations::subjects.delete'               => 'crvs.module.client_registrations::subjects.delete',
            'crvs.module.client_registrations::registrations.read'            => 'crvs.module.client_registrations::registrations.read',
            'crvs.module.client_registrations::registrations.write'           => 'crvs.module.client_registrations::registrations.write',
            'crvs.module.client_registrations::registrations.delete'          => 'crvs.module.client_registrations::registrations.delete',
            'crvs.module.client_registrations::actions.read'                  => 'crvs.module.client_registrations::actions.read',
            'crvs.module.client_registrations::actions.write'                 => 'crvs.module.client_registrations::actions.write',
            'crvs.module.client_registrations::actions.delete'                => 'crvs.module.client_registrations::actions.delete',
            'crvs.module.clients::clients.read'                               => 'crvs.module.clients::clients.read',
            'crvs.module.clients::clients.write'                              => 'crvs.module.clients::clients.write',
            'crvs.module.clients::clients.delete'                             => 'crvs.module.clients::clients.delete',
            'crvs.module.clients::fields.read'                                => 'crvs.module.clients::fields.read',
            'crvs.module.clients::fields.write'                               => 'crvs.module.clients::fields.write',
            'crvs.module.clients::fields.delete'                              => 'crvs.module.clients::fields.delete',
            'crvs.module.clients::roles.read'                                 => 'crvs.module.clients::roles.read',
            'crvs.module.clients::roles.write'                                => 'crvs.module.clients::roles.write',
            'crvs.module.clients::roles.delete'                               => 'crvs.module.clients::roles.delete',
            'crvs.module.clients::documents.read'                             => 'crvs.module.clients::documents.read',
            'crvs.module.clients::documents.write'                            => 'crvs.module.clients::documents.write',
            'crvs.module.clients::documents.delete'                           => 'crvs.module.clients::documents.delete',
            'crvs.module.clients::client_role_advisors.read'                  => 'crvs.module.clients::client_role_advisors.read',
            'crvs.module.clients::client_role_advisors.write'                 => 'crvs.module.clients::client_role_advisors.write',
            'crvs.module.clients::client_role_advisors.delete'                => 'crvs.module.clients::client_role_advisors.delete',
            'crvs.module.clients::client_role_department.read'                => 'crvs.module.clients::client_role_department.read',
            'crvs.module.clients::client_role_department.write'               => 'crvs.module.clients::client_role_department.write',
            'crvs.module.clients::client_role_department.delete'              => 'crvs.module.clients::client_role_department.delete',
            'crvs.module.clients::advisor.read'                               => 'crvs.module.clients::advisor.read',
            'crvs.module.clients::advisor.write'                              => 'crvs.module.clients::advisor.write',
            'crvs.module.clients::advisor.delete'                             => 'crvs.module.clients::advisor.delete',
            'crvs.module.clients::advisors.read'                              => 'crvs.module.clients::advisors.read',
            'crvs.module.clients::advisors.write'                             => 'crvs.module.clients::advisors.write',
            'crvs.module.clients::advisors.delete'                            => 'crvs.module.clients::advisors.delete',
            'crvs.module.clients::client_roles.read'                          => 'crvs.module.clients::client_roles.read',
            'crvs.module.clients::client_roles.write'                         => 'crvs.module.clients::client_roles.write',
            'crvs.module.clients::client_roles.delete'                        => 'crvs.module.clients::client_roles.delete',
            'crvs.module.clients::groups.read'                                => 'crvs.module.clients::groups.read',
            'crvs.module.clients::groups.write'                               => 'crvs.module.clients::groups.write',
            'crvs.module.clients::groups.delete'                              => 'crvs.module.clients::groups.delete',
            'crvs.module.clients::registrations.read'                         => 'crvs.module.clients::registrations.read',
            'crvs.module.clients::registrations.write'                        => 'crvs.module.clients::registrations.write',
            'crvs.module.clients::registrations.delete'                       => 'crvs.module.clients::registrations.delete',
            'crvs.module.clients::create_registrations_fields.read'           => 'crvs.module.clients::create_registrations_fields.read',
            'crvs.module.clients::create_registrations_fields.write'          => 'crvs.module.clients::create_registrations_fields.write',
            'crvs.module.clients::create_registrations_fields.delete'         => 'crvs.module.clients::create_registrations_fields.delete',
            'crvs.module.clients::reports.read'                               => 'crvs.module.clients::reports.read',
            'crvs.module.clients::reports.write'                              => 'crvs.module.clients::reports.write',
            'crvs.module.clients::reports.delete'                             => 'crvs.module.clients::reports.delete',
            'crvs.module.clients::instances.read'                             => 'crvs.module.clients::instances.read',
            'crvs.module.clients::instances.write'                            => 'crvs.module.clients::instances.write',
            'crvs.module.clients::instances.delete'                           => 'crvs.module.clients::instances.delete',
            'crvs.module.clients::dossiers.read'                              => 'crvs.module.clients::dossiers.read',
            'crvs.module.clients::dossiers.write'                             => 'crvs.module.clients::dossiers.write',
            'crvs.module.clients::dossiers.delete'                            => 'crvs.module.clients::dossiers.delete',
            'crvs.module.clients::client-advisor.read'                        => 'crvs.module.clients::client-advisor.read',
            'crvs.module.clients::client-advisor.write'                       => 'crvs.module.clients::client-advisor.write',
            'crvs.module.clients::client-advisor.delete'                      => 'crvs.module.clients::client-advisor.delete',
            'crvs.module.clients::client_advisor.read'                        => 'crvs.module.clients::client_advisor.read',
            'crvs.module.clients::client_advisor.write'                       => 'crvs.module.clients::client_advisor.write',
            'crvs.module.clients::client_advisor.delete'                      => 'crvs.module.clients::client_advisor.delete',
            'crvs.module.contacts::contacts.read'                             => 'crvs.module.contacts::contacts.read',
            'crvs.module.contacts::contacts.write'                            => 'crvs.module.contacts::contacts.write',
            'crvs.module.contacts::contacts.delete'                           => 'crvs.module.contacts::contacts.delete',
            'crvs.module.core::instances.read'                                => 'crvs.module.core::instances.read',
            'crvs.module.core::instances.write'                               => 'crvs.module.core::instances.write',
            'crvs.module.core::instances.delete'                              => 'crvs.module.core::instances.delete',
            'crvs.module.core::education_levels.read'                         => 'crvs.module.core::education_levels.read',
            'crvs.module.core::education_levels.write'                        => 'crvs.module.core::education_levels.write',
            'crvs.module.core::education_levels.delete'                       => 'crvs.module.core::education_levels.delete',
            'crvs.module.core::layout.sidebar'                                => 'crvs.module.core::layout.sidebar',
            'crvs.extension.courses_role_type::intake.read'                   => 'crvs.extension.courses_role_type::intake.read',
            'crvs.extension.courses_role_type::intake.write'                  => 'crvs.extension.courses_role_type::intake.write',
            'crvs.extension.courses_role_type::intake.delete'                 => 'crvs.extension.courses_role_type::intake.delete',
            'crvs.module.departments::user.select'                            => 'crvs.module.departments::user.select',
            'crvs.module.departments::user.deselect'                          => 'crvs.module.departments::user.deselect',
            'crvs.module.departments::user.all_departments'                   => 'crvs.module.departments::user.all_departments',
            'crvs.module.departments::user.select_disabled'                   => 'crvs.module.departments::user.select_disabled',
            'crvs.module.departments::department.read'                        => 'crvs.module.departments::department.read',
            'crvs.module.departments::department.write'                       => 'crvs.module.departments::department.write',
            'crvs.module.departments::department.delete'                      => 'crvs.module.departments::department.delete',
            'crvs.module.departments::department.enable'                      => 'crvs.module.departments::department.enable',
            'crvs.module.departments::department.disable'                     => 'crvs.module.departments::department.disable',
            'crvs.module.departments::associations.read'                      => 'crvs.module.departments::associations.read',
            'crvs.module.departments::associations.write'                     => 'crvs.module.departments::associations.write',
            'crvs.module.departments::associations.delete'                    => 'crvs.module.departments::associations.delete',
            'crvs.module.departments::linked_streams.form_edit_department'    => 'crvs.module.departments::linked_streams.form_edit_department',
            'crvs.module.departments::linked_streams.show_all_entries'        => 'crvs.module.departments::linked_streams.show_all_entries',
            'crvs.module.departments::settings.edit'                          => 'crvs.module.departments::settings.edit',
            'crvs.module.faq::Categories.read'                                => 'crvs.module.faq::Categories.read',
            'crvs.module.faq::Categories.write'                               => 'crvs.module.faq::Categories.write',
            'crvs.module.faq::Categories.delete'                              => 'crvs.module.faq::Categories.delete',
            'crvs.module.faq::Questions.read'                                 => 'crvs.module.faq::Questions.read',
            'crvs.module.faq::Questions.write'                                => 'crvs.module.faq::Questions.write',
            'crvs.module.faq::Questions.delete'                               => 'crvs.module.faq::Questions.delete',
            'crvs.module.files::files.read'                                   => 'crvs.module.files::files.read',
            'crvs.module.files::files.write'                                  => 'crvs.module.files::files.write',
            'crvs.module.files::files.delete'                                 => 'crvs.module.files::files.delete',
            'crvs.module.files::folders.read'                                 => 'crvs.module.files::folders.read',
            'crvs.module.files::folders.write'                                => 'crvs.module.files::folders.write',
            'crvs.module.files::folders.delete'                               => 'crvs.module.files::folders.delete',
            'crvs.module.files::disks.read'                                   => 'crvs.module.files::disks.read',
            'crvs.module.files::disks.write'                                  => 'crvs.module.files::disks.write',
            'crvs.module.files::disks.delete'                                 => 'crvs.module.files::disks.delete',
            'crvs.module.files::fields.manage'                                => 'crvs.module.files::fields.manage',
            'crvs.module.notes::notes.read'                                   => 'crvs.module.notes::notes.read',
            'crvs.module.notes::notes.write'                                  => 'crvs.module.notes::notes.write',
            'crvs.module.notes::notes.delete'                                 => 'crvs.module.notes::notes.delete',
            'crvs.extension.requester_role_type::requests.read'               => 'crvs.extension.requester_role_type::requests.read',
            'crvs.extension.requester_role_type::requests.write'              => 'crvs.extension.requester_role_type::requests.write',
            'crvs.extension.requester_role_type::requests.delete'             => 'crvs.extension.requester_role_type::requests.delete',
            'crvs.extension.requester_role_type::requests.match'              => 'crvs.extension.requester_role_type::requests.match',
            'crvs.extension.requester_role_type::request_categories.read'     => 'crvs.extension.requester_role_type::request_categories.read',
            'crvs.extension.requester_role_type::request_categories.write'    => 'crvs.extension.requester_role_type::request_categories.write',
            'crvs.extension.requester_role_type::request_categories.delete'   => 'crvs.extension.requester_role_type::request_categories.delete',
            'crvs.extension.requester_role_type::intake.read'                 => 'crvs.extension.requester_role_type::intake.read',
            'crvs.extension.requester_role_type::intake.write'                => 'crvs.extension.requester_role_type::intake.write',
            'crvs.extension.requester_role_type::intake.delete'               => 'crvs.extension.requester_role_type::intake.delete',
            'crvs.extension.requester_role_type::instances.read'              => 'crvs.extension.requester_role_type::instances.read',
            'crvs.extension.requester_role_type::instances.write'             => 'crvs.extension.requester_role_type::instances.write',
            'crvs.extension.requester_role_type::instances.delete'            => 'crvs.extension.requester_role_type::instances.delete',
            'crvs.extension.requester_role_type::groups.read'                 => 'crvs.extension.requester_role_type::groups.read',
            'crvs.extension.requester_role_type::groups.write'                => 'crvs.extension.requester_role_type::groups.write',
            'crvs.extension.requester_role_type::groups.delete'               => 'crvs.extension.requester_role_type::groups.delete',
            'crvs.extension.requester_role_type::categories.read'             => 'crvs.extension.requester_role_type::categories.read',
            'crvs.extension.requester_role_type::categories.write'            => 'crvs.extension.requester_role_type::categories.write',
            'crvs.extension.requester_role_type::categories.delete'           => 'crvs.extension.requester_role_type::categories.delete',
            'crvs.extension.requester_role_type::matches.read'                => 'crvs.extension.requester_role_type::matches.read',
            'crvs.extension.requester_role_type::matches.write'               => 'crvs.extension.requester_role_type::matches.write',
            'crvs.extension.requester_role_type::matches.delete'              => 'crvs.extension.requester_role_type::matches.delete',
            'crvs.extension.requester_role_type::reason_closed.read'          => 'crvs.extension.requester_role_type::reason_closed.read',
            'crvs.extension.requester_role_type::reason_closed.write'         => 'crvs.extension.requester_role_type::reason_closed.write',
            'crvs.extension.requester_role_type::reason_closed.delete'        => 'crvs.extension.requester_role_type::reason_closed.delete',
            'crvs.extension.requester_role_type::reason_unfilled.read'        => 'crvs.extension.requester_role_type::reason_unfilled.read',
            'crvs.extension.requester_role_type::reason_unfilled.write'       => 'crvs.extension.requester_role_type::reason_unfilled.write',
            'crvs.extension.requester_role_type::reason_unfilled.delete'      => 'crvs.extension.requester_role_type::reason_unfilled.delete',
            'crvs.extension.requester_role_type::caretakers.read'             => 'crvs.extension.requester_role_type::caretakers.read',
            'crvs.extension.requester_role_type::caretakers.write'            => 'crvs.extension.requester_role_type::caretakers.write',
            'crvs.extension.requester_role_type::caretakers.delete'           => 'crvs.extension.requester_role_type::caretakers.delete',
            'crvs.extension.volunteer_role_type::intake.read'                 => 'crvs.extension.volunteer_role_type::intake.read',
            'crvs.extension.volunteer_role_type::intake.write'                => 'crvs.extension.volunteer_role_type::intake.write',
            'crvs.extension.volunteer_role_type::intake.delete'               => 'crvs.extension.volunteer_role_type::intake.delete',
            'examples.module.ex1::departments.read'                           => 'examples.module.ex1::departments.read',
            'examples.module.ex1::departments.write'                          => 'examples.module.ex1::departments.write',
            'examples.module.ex1::departments.delete'                         => 'examples.module.ex1::departments.delete',
            'pyro.module.activity_log::activity.read'                         => 'pyro.module.activity_log::activity.read',
            'pyro.module.activity_log::activity.write'                        => 'pyro.module.activity_log::activity.write',
            'pyro.module.activity_log::activity.delete'                       => 'pyro.module.activity_log::activity.delete',
            'pyro.module.menus::menus.read'                                   => 'pyro.module.menus::menus.read',
            'pyro.module.menus::menus.write'                                  => 'pyro.module.menus::menus.write',
            'pyro.module.menus::menus.delete'                                 => 'pyro.module.menus::menus.delete',
            'pyro.module.menus::links.read'                                   => 'pyro.module.menus::links.read',
            'pyro.module.menus::links.write'                                  => 'pyro.module.menus::links.write',
            'pyro.module.menus::links.delete'                                 => 'pyro.module.menus::links.delete',
            'pyro.module.news::items.read'                                    => 'pyro.module.news::items.read',
            'pyro.module.news::items.write'                                   => 'pyro.module.news::items.write',
            'pyro.module.news::items.delete'                                  => 'pyro.module.news::items.delete',
            'pyro.module.reactable::action.read'                              => 'pyro.module.reactable::action.read',
            'pyro.module.reactable::action.write'                             => 'pyro.module.reactable::action.write',
            'pyro.module.reactable::action.delete'                            => 'pyro.module.reactable::action.delete',
            'pyro.module.reactable::triggers.read'                            => 'pyro.module.reactable::triggers.read',
            'pyro.module.reactable::triggers.write'                           => 'pyro.module.reactable::triggers.write',
            'pyro.module.reactable::triggers.delete'                          => 'pyro.module.reactable::triggers.delete',
            'pyro.module.reactable::actions.read'                             => 'pyro.module.reactable::actions.read',
            'pyro.module.reactable::actions.write'                            => 'pyro.module.reactable::actions.write',
            'pyro.module.reactable::actions.delete'                           => 'pyro.module.reactable::actions.delete',
            'pyro.module.reactable::trigger.read'                             => 'pyro.module.reactable::trigger.read',
            'pyro.module.reactable::trigger.write'                            => 'pyro.module.reactable::trigger.write',
            'pyro.module.reactable::trigger.delete'                           => 'pyro.module.reactable::trigger.delete',
        ]
    }
}
