<?php /** @noinspection AutoloadingIssuesInspection *//** @noinspection PhpUnused */

namespace Pyro\IdeHelper\Examples;

class PermissionsExamples
{
    public static function permissions()
    {
        return [
        'streams::maintenance.access',
'streams::control_panel.access',
'anomaly.module.settings::settings.write',
'anomaly.module.preferences::preferences.write',
'anomaly.module.repeaters::repeaters.read',
'anomaly.module.repeaters::repeaters.write',
'anomaly.module.repeaters::repeaters.delete',
'anomaly.module.repeaters::repeaters.fields',
'anomaly.module.repeaters::fields.manage',
'anomaly.module.repeaters::repeaters.read',
'anomaly.module.repeaters::repeaters.write',
'anomaly.module.repeaters::repeaters.delete',
'anomaly.module.repeaters::repeaters.fields',
'anomaly.module.repeaters::fields.manage',
'anomaly.module.addons::modules.read',
'anomaly.module.addons::modules.manage',
'anomaly.module.addons::themes.read',
'anomaly.module.addons::themes.manage',
'anomaly.module.addons::plugins.read',
'anomaly.module.addons::plugins.manage',
'anomaly.module.addons::extensions.read',
'anomaly.module.addons::extensions.manage',
'anomaly.module.addons::field_types.read',
'anomaly.module.addons::field_types.manage',
'anomaly.module.addons::addons.read',
'anomaly.module.addons::addons.write',
'anomaly.module.addons::addons.delete',
'anomaly.module.addons::repositories.read',
'anomaly.module.addons::repositories.write',
'anomaly.module.addons::repositories.delete',
'anomaly.module.blocks::areas.read',
'anomaly.module.blocks::areas.write',
'anomaly.module.blocks::areas.delete',
'anomaly.module.blocks::blocks.read',
'anomaly.module.blocks::blocks.write',
'anomaly.module.blocks::blocks.delete',
'anomaly.module.dashboard::dashboards.read',
'anomaly.module.dashboard::dashboards.write',
'anomaly.module.dashboard::dashboards.delete',
'anomaly.module.dashboard::widgets.read',
'anomaly.module.dashboard::widgets.write',
'anomaly.module.dashboard::widgets.delete',
'anomaly.module.files::files.read',
'anomaly.module.files::files.write',
'anomaly.module.files::files.delete',
'anomaly.module.files::folders.read',
'anomaly.module.files::folders.write',
'anomaly.module.files::folders.delete',
'anomaly.module.files::disks.read',
'anomaly.module.files::disks.write',
'anomaly.module.files::disks.delete',
'anomaly.module.files::fields.manage',
'anomaly.module.navigation::menus.read',
'anomaly.module.navigation::menus.write',
'anomaly.module.navigation::menus.delete',
'anomaly.module.navigation::links.read',
'anomaly.module.navigation::links.write',
'anomaly.module.navigation::links.delete',
'anomaly.module.posts::posts.read',
'anomaly.module.posts::posts.write',
'anomaly.module.posts::posts.delete',
'anomaly.module.posts::posts.preview',
'anomaly.module.posts::categories.read',
'anomaly.module.posts::categories.write',
            'anomaly.module.posts::categories.delete',
            'anomaly.module.posts::types.read',
            'anomaly.module.posts::types.write',
            'anomaly.module.posts::types.delete',
            'anomaly.module.posts::fields.manage',
            'anomaly.module.search::items.read',
            'anomaly.module.search::items.write',
            'anomaly.module.search::items.delete',
            'anomaly.module.streams::streams.access',
            'anomaly.module.streams::categories.read',
            'anomaly.module.streams::categories.write',
            'anomaly.module.streams::categories.delete',
            'anomaly.module.streams::posts.read',
            'anomaly.module.streams::posts.write',
            'anomaly.module.streams::posts.delete',
            'anomaly.module.streams::types.read',
            'anomaly.module.streams::types.write',
            'anomaly.module.streams::types.delete',
            'anomaly.module.streams::default_posts.read',
            'anomaly.module.streams::default_posts.write',
            'anomaly.module.streams::default_posts.delete',
            'anomaly.module.streams::comments.read',
            'anomaly.module.streams::comments.write',
            'anomaly.module.streams::comments.delete',
            'anomaly.module.system::system.read',
            'anomaly.module.system::system.write',
            'anomaly.module.system::system.delete',
            'anomaly.module.users::users.read',
            'anomaly.module.users::users.write',
            'anomaly.module.users::users.write_admins',
            'anomaly.module.users::users.impersonate',
            'anomaly.module.users::users.delete',
            'anomaly.module.users::users.manage_permissions',
            'anomaly.module.users::roles.read',
'anomaly.module.users::roles.write',
            'anomaly.module.users::roles.delete',
            'anomaly.module.users::fields.manage',
            'anomaly.module.users::settings.manage',
            'anomaly.module.variables::variables.read',
            'anomaly.module.variables::variables.write',
            'anomaly.module.variables::variables.delete',
            'anomaly.module.variables::groups.read',
            'anomaly.module.variables::groups.write',
            'anomaly.module.variables::groups.delete',
            'anomaly.module.variables::fields.manage',
            'oaty.module.graphql::events.read',
            'oaty.module.graphql::events.write',
            'oaty.module.graphql::events.delete',
            'oaty.module.graphql::event_signups.read',
            'oaty.module.graphql::event_signups.write',
            'oaty.module.graphql::event_signups.delete',
            'oaty.module.events::events.read',
            'oaty.module.events::events.write',
            'oaty.module.events::events.delete',
            'oaty.module.events::signups.read',
            'oaty.module.events::signups.write',
            'oaty.module.events::signups.delete',
            'anomaly.module.pages::pages.read',
            'anomaly.module.pages::pages.write',
            'anomaly.module.pages::pages.delete',
            'anomaly.module.pages::pages.preview',
            'anomaly.module.pages::types.read',
            'anomaly.module.pages::types.write',
            'anomaly.module.pages::types.delete',
            'anomaly.module.pages::types.fields',
            'anomaly.module.pages::fields.manage',
            'anomaly.module.redirects::redirects.read',
'anomaly.module.redirects::redirects.write',
'anomaly.module.redirects::redirects.delete',
'anomaly.module.redirects::domains.read',
'anomaly.module.redirects::domains.write',
'anomaly.module.redirects::domains.delete',
        ];
    }

    public static function permissionsAssoc()
    {
        return [
            'streams::maintenance.access' => 'streams::maintenance.access',
            'streams::control_panel.access' => 'streams::control_panel.access',
            'anomaly.module.settings::settings.write' => 'anomaly.module.settings::settings.write',
            'anomaly.module.preferences::preferences.write' => 'anomaly.module.preferences::preferences.write',
            'anomaly.module.repeaters::repeaters.read' => 'anomaly.module.repeaters::repeaters.read',
            'anomaly.module.repeaters::repeaters.write' => 'anomaly.module.repeaters::repeaters.write',
            'anomaly.module.repeaters::repeaters.delete' => 'anomaly.module.repeaters::repeaters.delete',
            'anomaly.module.repeaters::repeaters.fields' => 'anomaly.module.repeaters::repeaters.fields',
            'anomaly.module.repeaters::fields.manage' => 'anomaly.module.repeaters::fields.manage',
            'anomaly.module.repeaters::repeaters.read' => 'anomaly.module.repeaters::repeaters.read',
            'anomaly.module.repeaters::repeaters.write' => 'anomaly.module.repeaters::repeaters.write',
            'anomaly.module.repeaters::repeaters.delete' => 'anomaly.module.repeaters::repeaters.delete',
            'anomaly.module.repeaters::repeaters.fields' => 'anomaly.module.repeaters::repeaters.fields',
            'anomaly.module.repeaters::fields.manage' => 'anomaly.module.repeaters::fields.manage',
            'anomaly.module.addons::modules.read' => 'anomaly.module.addons::modules.read',
            'anomaly.module.addons::modules.manage' => 'anomaly.module.addons::modules.manage',
            'anomaly.module.addons::themes.read' => 'anomaly.module.addons::themes.read',
            'anomaly.module.addons::themes.manage' => 'anomaly.module.addons::themes.manage',
            'anomaly.module.addons::plugins.read' => 'anomaly.module.addons::plugins.read',
            'anomaly.module.addons::plugins.manage' => 'anomaly.module.addons::plugins.manage',
            'anomaly.module.addons::extensions.read' => 'anomaly.module.addons::extensions.read',
            'anomaly.module.addons::extensions.manage' => 'anomaly.module.addons::extensions.manage',
            'anomaly.module.addons::field_types.read' => 'anomaly.module.addons::field_types.read',
            'anomaly.module.addons::field_types.manage' => 'anomaly.module.addons::field_types.manage',
            'anomaly.module.addons::addons.read' => 'anomaly.module.addons::addons.read',
            'anomaly.module.addons::addons.write' => 'anomaly.module.addons::addons.write',
            'anomaly.module.addons::addons.delete' => 'anomaly.module.addons::addons.delete',
            'anomaly.module.addons::repositories.read' => 'anomaly.module.addons::repositories.read',
            'anomaly.module.addons::repositories.write' => 'anomaly.module.addons::repositories.write',
            'anomaly.module.addons::repositories.delete' => 'anomaly.module.addons::repositories.delete',
            'anomaly.module.blocks::areas.read' => 'anomaly.module.blocks::areas.read',
            'anomaly.module.blocks::areas.write' => 'anomaly.module.blocks::areas.write',
            'anomaly.module.blocks::areas.delete' => 'anomaly.module.blocks::areas.delete',
            'anomaly.module.blocks::blocks.read' => 'anomaly.module.blocks::blocks.read',
            'anomaly.module.blocks::blocks.write' => 'anomaly.module.blocks::blocks.write',
            'anomaly.module.blocks::blocks.delete' => 'anomaly.module.blocks::blocks.delete',
            'anomaly.module.dashboard::dashboards.read' => 'anomaly.module.dashboard::dashboards.read',
            'anomaly.module.dashboard::dashboards.write' => 'anomaly.module.dashboard::dashboards.write',
            'anomaly.module.dashboard::dashboards.delete' => 'anomaly.module.dashboard::dashboards.delete',
            'anomaly.module.dashboard::widgets.read' => 'anomaly.module.dashboard::widgets.read',
            'anomaly.module.dashboard::widgets.write' => 'anomaly.module.dashboard::widgets.write',
            'anomaly.module.dashboard::widgets.delete' => 'anomaly.module.dashboard::widgets.delete',
            'anomaly.module.files::files.read' => 'anomaly.module.files::files.read',
            'anomaly.module.files::files.write' => 'anomaly.module.files::files.write',
            'anomaly.module.files::files.delete' => 'anomaly.module.files::files.delete',
            'anomaly.module.files::folders.read' => 'anomaly.module.files::folders.read',
            'anomaly.module.files::folders.write' => 'anomaly.module.files::folders.write',
            'anomaly.module.files::folders.delete' => 'anomaly.module.files::folders.delete',
            'anomaly.module.files::disks.read' => 'anomaly.module.files::disks.read',
            'anomaly.module.files::disks.write' => 'anomaly.module.files::disks.write',
            'anomaly.module.files::disks.delete' => 'anomaly.module.files::disks.delete',
            'anomaly.module.files::fields.manage' => 'anomaly.module.files::fields.manage',
            'anomaly.module.navigation::menus.read' => 'anomaly.module.navigation::menus.read',
            'anomaly.module.navigation::menus.write'         => 'anomaly.module.navigation::menus.write',
            'anomaly.module.navigation::menus.delete'        => 'anomaly.module.navigation::menus.delete',
            'anomaly.module.navigation::links.read'          => 'anomaly.module.navigation::links.read',
            'anomaly.module.navigation::links.write'         => 'anomaly.module.navigation::links.write',
            'anomaly.module.navigation::links.delete'        => 'anomaly.module.navigation::links.delete',
            'anomaly.module.posts::posts.read'               => 'anomaly.module.posts::posts.read',
            'anomaly.module.posts::posts.write'              => 'anomaly.module.posts::posts.write',
            'anomaly.module.posts::posts.delete'             => 'anomaly.module.posts::posts.delete',
            'anomaly.module.posts::posts.preview'            => 'anomaly.module.posts::posts.preview',
            'anomaly.module.posts::categories.read'          => 'anomaly.module.posts::categories.read',
            'anomaly.module.posts::categories.write'         => 'anomaly.module.posts::categories.write',
            'anomaly.module.posts::categories.delete'        => 'anomaly.module.posts::categories.delete',
            'anomaly.module.posts::types.read'               => 'anomaly.module.posts::types.read',
            'anomaly.module.posts::types.write'              => 'anomaly.module.posts::types.write',
            'anomaly.module.posts::types.delete'             => 'anomaly.module.posts::types.delete',
            'anomaly.module.posts::fields.manage'            => 'anomaly.module.posts::fields.manage',
            'anomaly.module.search::items.read'              => 'anomaly.module.search::items.read',
            'anomaly.module.search::items.write'             => 'anomaly.module.search::items.write',
            'anomaly.module.search::items.delete'            => 'anomaly.module.search::items.delete',
            'anomaly.module.streams::streams.access'         => 'anomaly.module.streams::streams.access',
            'anomaly.module.streams::categories.read'        => 'anomaly.module.streams::categories.read',
            'anomaly.module.streams::categories.write'       => 'anomaly.module.streams::categories.write',
            'anomaly.module.streams::categories.delete'      => 'anomaly.module.streams::categories.delete',
            'anomaly.module.streams::posts.read'             => 'anomaly.module.streams::posts.read',
            'anomaly.module.streams::posts.write'            => 'anomaly.module.streams::posts.write',
            'anomaly.module.streams::posts.delete'           => 'anomaly.module.streams::posts.delete',
            'anomaly.module.streams::types.read'             => 'anomaly.module.streams::types.read',
            'anomaly.module.streams::types.write'            => 'anomaly.module.streams::types.write',
            'anomaly.module.streams::types.delete'           => 'anomaly.module.streams::types.delete',
            'anomaly.module.streams::default_posts.read'     => 'anomaly.module.streams::default_posts.read',
            'anomaly.module.streams::default_posts.write'    => 'anomaly.module.streams::default_posts.write',
            'anomaly.module.streams::default_posts.delete'   => 'anomaly.module.streams::default_posts.delete',
            'anomaly.module.streams::comments.read'          => 'anomaly.module.streams::comments.read',
            'anomaly.module.streams::comments.write'         => 'anomaly.module.streams::comments.write',
            'anomaly.module.streams::comments.delete'        => 'anomaly.module.streams::comments.delete',
            'anomaly.module.system::system.read'             => 'anomaly.module.system::system.read',
            'anomaly.module.system::system.write'            => 'anomaly.module.system::system.write',
            'anomaly.module.system::system.delete'           => 'anomaly.module.system::system.delete',
            'anomaly.module.users::users.read'               => 'anomaly.module.users::users.read',
            'anomaly.module.users::users.write'              => 'anomaly.module.users::users.write',
            'anomaly.module.users::users.write_admins'       => 'anomaly.module.users::users.write_admins',
            'anomaly.module.users::users.impersonate'        => 'anomaly.module.users::users.impersonate',
            'anomaly.module.users::users.delete'             => 'anomaly.module.users::users.delete',
            'anomaly.module.users::users.manage_permissions' => 'anomaly.module.users::users.manage_permissions',
            'anomaly.module.users::roles.read'               => 'anomaly.module.users::roles.read',
            'anomaly.module.users::roles.write'              => 'anomaly.module.users::roles.write',
            'anomaly.module.users::roles.delete'             => 'anomaly.module.users::roles.delete',
            'anomaly.module.users::fields.manage'            => 'anomaly.module.users::fields.manage',
            'anomaly.module.users::settings.manage'          => 'anomaly.module.users::settings.manage',
            'anomaly.module.variables::variables.read'       => 'anomaly.module.variables::variables.read',
            'anomaly.module.variables::variables.write'      => 'anomaly.module.variables::variables.write',
            'anomaly.module.variables::variables.delete'     => 'anomaly.module.variables::variables.delete',
            'anomaly.module.variables::groups.read'          => 'anomaly.module.variables::groups.read',
            'anomaly.module.variables::groups.write'         => 'anomaly.module.variables::groups.write',
            'anomaly.module.variables::groups.delete'        => 'anomaly.module.variables::groups.delete',
            'anomaly.module.variables::fields.manage'        => 'anomaly.module.variables::fields.manage',
            'oaty.module.graphql::events.read'               => 'oaty.module.graphql::events.read',
            'oaty.module.graphql::events.write'              => 'oaty.module.graphql::events.write',
            'oaty.module.graphql::events.delete'             => 'oaty.module.graphql::events.delete',
            'oaty.module.graphql::event_signups.read'        => 'oaty.module.graphql::event_signups.read',
            'oaty.module.graphql::event_signups.write'       => 'oaty.module.graphql::event_signups.write',
            'oaty.module.graphql::event_signups.delete'      => 'oaty.module.graphql::event_signups.delete',
            'oaty.module.events::events.read'                => 'oaty.module.events::events.read',
            'oaty.module.events::events.write'               => 'oaty.module.events::events.write',
            'oaty.module.events::events.delete'              => 'oaty.module.events::events.delete',
            'oaty.module.events::signups.read'               => 'oaty.module.events::signups.read',
            'oaty.module.events::signups.write'              => 'oaty.module.events::signups.write',
            'oaty.module.events::signups.delete'             => 'oaty.module.events::signups.delete',
            'anomaly.module.pages::pages.read'               => 'anomaly.module.pages::pages.read',
            'anomaly.module.pages::pages.write'              => 'anomaly.module.pages::pages.write',
            'anomaly.module.pages::pages.delete'             => 'anomaly.module.pages::pages.delete',
            'anomaly.module.pages::pages.preview'            => 'anomaly.module.pages::pages.preview',
            'anomaly.module.pages::types.read'               => 'anomaly.module.pages::types.read',
            'anomaly.module.pages::types.write'              => 'anomaly.module.pages::types.write',
            'anomaly.module.pages::types.delete'             => 'anomaly.module.pages::types.delete',
            'anomaly.module.pages::types.fields'             => 'anomaly.module.pages::types.fields',
            'anomaly.module.pages::fields.manage'            => 'anomaly.module.pages::fields.manage',
            'anomaly.module.redirects::redirects.read'       => 'anomaly.module.redirects::redirects.read',
            'anomaly.module.redirects::redirects.write'      => 'anomaly.module.redirects::redirects.write',
            'anomaly.module.redirects::redirects.delete'     => 'anomaly.module.redirects::redirects.delete',
            'anomaly.module.redirects::domains.read'         => 'anomaly.module.redirects::domains.read',
            'anomaly.module.redirects::domains.write'        => 'anomaly.module.redirects::domains.write',
            'anomaly.module.redirects::domains.delete'       => 'anomaly.module.redirects::domains.delete',
        ];
    }
}
