<?php /** @noinspection AutoloadingIssuesInspection *//** @noinspection PhpUnused */

namespace Pyro\IdeHelper\Examples;

class PermissionsExamples
{
    public static function permissions()
    {
        return [
        'streams::maintenance.access',
'streams::control_panel.access',
'streams::control_panel.sidebar',
'anomaly.module.settings::settings.write',
'anomaly.module.preferences::preferences.write',
'anomaly.module.blocks::areas.read',
'anomaly.module.blocks::areas.write',
'anomaly.module.blocks::areas.delete',
'anomaly.module.blocks::blocks.read',
'anomaly.module.blocks::blocks.write',
'anomaly.module.blocks::blocks.delete',
'anomaly.module.dashboard::dashboards.read',
'anomaly.module.dashboard::dashboards.write',
'anomaly.module.dashboard::dashboards.delete',
'anomaly.module.dashboard::widgets.read',
'anomaly.module.dashboard::widgets.write',
'anomaly.module.dashboard::widgets.delete',
'anomaly.module.files::files.read',
'anomaly.module.files::files.write',
'anomaly.module.files::files.delete',
'anomaly.module.files::folders.read',
'anomaly.module.files::folders.write',
'anomaly.module.files::folders.delete',
'anomaly.module.files::disks.read',
'anomaly.module.files::disks.write',
'anomaly.module.files::disks.delete',
'anomaly.module.files::fields.manage',
'anomaly.module.grids::grids.read',
'anomaly.module.grids::grids.write',
'anomaly.module.grids::grids.delete',
'anomaly.module.grids::grids.fields',
'anomaly.module.grids::fields.manage',
'anomaly.module.navigation::menus.read',
'anomaly.module.navigation::menus.write',
'anomaly.module.navigation::menus.delete',
'anomaly.module.navigation::links.read',
'anomaly.module.navigation::links.write',
'anomaly.module.navigation::links.delete',
'anomaly.module.pages::pages.read',
'anomaly.module.pages::pages.write',
'anomaly.module.pages::pages.delete',
'anomaly.module.pages::pages.preview',
'anomaly.module.pages::types.read',
'anomaly.module.pages::types.write',
'anomaly.module.pages::types.delete',
'anomaly.module.pages::types.fields',
'anomaly.module.pages::fields.manage',
'anomaly.module.redirects::redirects.read',
'anomaly.module.redirects::redirects.write',
'anomaly.module.redirects::redirects.delete',
'anomaly.module.redirects::domains.read',
'anomaly.module.redirects::domains.write',
'anomaly.module.redirects::domains.delete',
'anomaly.module.repeaters::repeaters.read',
'anomaly.module.repeaters::repeaters.write',
'anomaly.module.repeaters::repeaters.delete',
'anomaly.module.repeaters::repeaters.fields',
'anomaly.module.repeaters::fields.manage',
'anomaly.module.search::items.read',
'anomaly.module.search::items.write',
'anomaly.module.search::items.delete',
'anomaly.module.users::users.read',
'anomaly.module.users::users.write',
'anomaly.module.users::users.write_admins',
'anomaly.module.users::users.impersonate',
'anomaly.module.users::users.delete',
'anomaly.module.users::roles.read',
'anomaly.module.users::roles.write',
'anomaly.module.users::roles.delete',
'anomaly.module.users::fields.manage',
'anomaly.module.users::settings.manage',
'crvs.module.core::instances.read',
'crvs.module.core::instances.write',
'crvs.module.core::instances.delete',
'crvs.module.core::education_levels.read',
'crvs.module.core::education_levels.write',
'crvs.module.core::education_levels.delete',
'crvs.module.core::layout.sidebar',
'pyro.module.activity_log::activity.read',
'pyro.module.activity_log::activity.write',
'pyro.module.activity_log::activity.delete',
'pyro.module.menus::menus.read',
'pyro.module.menus::menus.write',
'pyro.module.menus::menus.delete',
'pyro.module.menus::links.read',
'pyro.module.menus::links.write',
'pyro.module.menus::links.delete',
'crvs.module.ci::projects.read',
'crvs.module.ci::projects.write',
'crvs.module.ci::projects.delete',
'crvs.module.ci::hosts.read',
'crvs.module.ci::hosts.write',
'crvs.module.ci::hosts.delete',
'crvs.module.ci::servers.read',
'crvs.module.ci::servers.write',
'crvs.module.ci::servers.delete',
'crvs.module.ci::keys.read',
'crvs.module.ci::keys.write',
'crvs.module.ci::keys.delete',
'crvs.module.ci::vcs.read',
'crvs.module.ci::vcs.write',
'crvs.module.ci::vcs.delete',
'crvs.module.ci::teams.read',
'crvs.module.ci::teams.write',
'crvs.module.ci::teams.delete',
'crvs.module.ci::credentials.read',
'crvs.module.ci::credentials.write',
'crvs.module.ci::credentials.delete',
        ];
    }

    public static function permissionsAssoc()
    {
        return [
        'streams::maintenance.access' => 'streams::maintenance.access',
'streams::control_panel.access' => 'streams::control_panel.access',
'streams::control_panel.sidebar' => 'streams::control_panel.sidebar',
'anomaly.module.settings::settings.write' => 'anomaly.module.settings::settings.write',
'anomaly.module.preferences::preferences.write' => 'anomaly.module.preferences::preferences.write',
'anomaly.module.blocks::areas.read' => 'anomaly.module.blocks::areas.read',
'anomaly.module.blocks::areas.write' => 'anomaly.module.blocks::areas.write',
'anomaly.module.blocks::areas.delete' => 'anomaly.module.blocks::areas.delete',
'anomaly.module.blocks::blocks.read' => 'anomaly.module.blocks::blocks.read',
'anomaly.module.blocks::blocks.write' => 'anomaly.module.blocks::blocks.write',
'anomaly.module.blocks::blocks.delete' => 'anomaly.module.blocks::blocks.delete',
'anomaly.module.dashboard::dashboards.read' => 'anomaly.module.dashboard::dashboards.read',
'anomaly.module.dashboard::dashboards.write' => 'anomaly.module.dashboard::dashboards.write',
'anomaly.module.dashboard::dashboards.delete' => 'anomaly.module.dashboard::dashboards.delete',
'anomaly.module.dashboard::widgets.read' => 'anomaly.module.dashboard::widgets.read',
'anomaly.module.dashboard::widgets.write' => 'anomaly.module.dashboard::widgets.write',
'anomaly.module.dashboard::widgets.delete' => 'anomaly.module.dashboard::widgets.delete',
'anomaly.module.files::files.read' => 'anomaly.module.files::files.read',
'anomaly.module.files::files.write' => 'anomaly.module.files::files.write',
'anomaly.module.files::files.delete' => 'anomaly.module.files::files.delete',
'anomaly.module.files::folders.read' => 'anomaly.module.files::folders.read',
'anomaly.module.files::folders.write' => 'anomaly.module.files::folders.write',
'anomaly.module.files::folders.delete' => 'anomaly.module.files::folders.delete',
'anomaly.module.files::disks.read' => 'anomaly.module.files::disks.read',
'anomaly.module.files::disks.write' => 'anomaly.module.files::disks.write',
'anomaly.module.files::disks.delete' => 'anomaly.module.files::disks.delete',
'anomaly.module.files::fields.manage' => 'anomaly.module.files::fields.manage',
'anomaly.module.grids::grids.read' => 'anomaly.module.grids::grids.read',
'anomaly.module.grids::grids.write' => 'anomaly.module.grids::grids.write',
'anomaly.module.grids::grids.delete' => 'anomaly.module.grids::grids.delete',
'anomaly.module.grids::grids.fields' => 'anomaly.module.grids::grids.fields',
'anomaly.module.grids::fields.manage' => 'anomaly.module.grids::fields.manage',
'anomaly.module.navigation::menus.read' => 'anomaly.module.navigation::menus.read',
'anomaly.module.navigation::menus.write' => 'anomaly.module.navigation::menus.write',
'anomaly.module.navigation::menus.delete' => 'anomaly.module.navigation::menus.delete',
'anomaly.module.navigation::links.read' => 'anomaly.module.navigation::links.read',
'anomaly.module.navigation::links.write' => 'anomaly.module.navigation::links.write',
'anomaly.module.navigation::links.delete' => 'anomaly.module.navigation::links.delete',
'anomaly.module.pages::pages.read' => 'anomaly.module.pages::pages.read',
'anomaly.module.pages::pages.write' => 'anomaly.module.pages::pages.write',
'anomaly.module.pages::pages.delete' => 'anomaly.module.pages::pages.delete',
'anomaly.module.pages::pages.preview' => 'anomaly.module.pages::pages.preview',
'anomaly.module.pages::types.read' => 'anomaly.module.pages::types.read',
'anomaly.module.pages::types.write' => 'anomaly.module.pages::types.write',
'anomaly.module.pages::types.delete' => 'anomaly.module.pages::types.delete',
'anomaly.module.pages::types.fields' => 'anomaly.module.pages::types.fields',
'anomaly.module.pages::fields.manage' => 'anomaly.module.pages::fields.manage',
'anomaly.module.redirects::redirects.read' => 'anomaly.module.redirects::redirects.read',
'anomaly.module.redirects::redirects.write' => 'anomaly.module.redirects::redirects.write',
'anomaly.module.redirects::redirects.delete' => 'anomaly.module.redirects::redirects.delete',
'anomaly.module.redirects::domains.read' => 'anomaly.module.redirects::domains.read',
'anomaly.module.redirects::domains.write' => 'anomaly.module.redirects::domains.write',
'anomaly.module.redirects::domains.delete' => 'anomaly.module.redirects::domains.delete',
'anomaly.module.repeaters::repeaters.read' => 'anomaly.module.repeaters::repeaters.read',
'anomaly.module.repeaters::repeaters.write' => 'anomaly.module.repeaters::repeaters.write',
'anomaly.module.repeaters::repeaters.delete' => 'anomaly.module.repeaters::repeaters.delete',
'anomaly.module.repeaters::repeaters.fields' => 'anomaly.module.repeaters::repeaters.fields',
'anomaly.module.repeaters::fields.manage' => 'anomaly.module.repeaters::fields.manage',
'anomaly.module.search::items.read' => 'anomaly.module.search::items.read',
'anomaly.module.search::items.write' => 'anomaly.module.search::items.write',
'anomaly.module.search::items.delete' => 'anomaly.module.search::items.delete',
'anomaly.module.users::users.read' => 'anomaly.module.users::users.read',
'anomaly.module.users::users.write' => 'anomaly.module.users::users.write',
'anomaly.module.users::users.write_admins' => 'anomaly.module.users::users.write_admins',
'anomaly.module.users::users.impersonate' => 'anomaly.module.users::users.impersonate',
'anomaly.module.users::users.delete' => 'anomaly.module.users::users.delete',
'anomaly.module.users::roles.read' => 'anomaly.module.users::roles.read',
'anomaly.module.users::roles.write' => 'anomaly.module.users::roles.write',
'anomaly.module.users::roles.delete' => 'anomaly.module.users::roles.delete',
'anomaly.module.users::fields.manage' => 'anomaly.module.users::fields.manage',
'anomaly.module.users::settings.manage' => 'anomaly.module.users::settings.manage',
'crvs.module.core::instances.read' => 'crvs.module.core::instances.read',
'crvs.module.core::instances.write' => 'crvs.module.core::instances.write',
'crvs.module.core::instances.delete' => 'crvs.module.core::instances.delete',
'crvs.module.core::education_levels.read' => 'crvs.module.core::education_levels.read',
'crvs.module.core::education_levels.write' => 'crvs.module.core::education_levels.write',
'crvs.module.core::education_levels.delete' => 'crvs.module.core::education_levels.delete',
'crvs.module.core::layout.sidebar' => 'crvs.module.core::layout.sidebar',
'pyro.module.activity_log::activity.read' => 'pyro.module.activity_log::activity.read',
'pyro.module.activity_log::activity.write' => 'pyro.module.activity_log::activity.write',
'pyro.module.activity_log::activity.delete' => 'pyro.module.activity_log::activity.delete',
'pyro.module.menus::menus.read' => 'pyro.module.menus::menus.read',
'pyro.module.menus::menus.write' => 'pyro.module.menus::menus.write',
'pyro.module.menus::menus.delete' => 'pyro.module.menus::menus.delete',
'pyro.module.menus::links.read' => 'pyro.module.menus::links.read',
'pyro.module.menus::links.write' => 'pyro.module.menus::links.write',
'pyro.module.menus::links.delete' => 'pyro.module.menus::links.delete',
'crvs.module.ci::projects.read' => 'crvs.module.ci::projects.read',
'crvs.module.ci::projects.write' => 'crvs.module.ci::projects.write',
'crvs.module.ci::projects.delete' => 'crvs.module.ci::projects.delete',
'crvs.module.ci::hosts.read' => 'crvs.module.ci::hosts.read',
'crvs.module.ci::hosts.write' => 'crvs.module.ci::hosts.write',
'crvs.module.ci::hosts.delete' => 'crvs.module.ci::hosts.delete',
'crvs.module.ci::servers.read' => 'crvs.module.ci::servers.read',
'crvs.module.ci::servers.write' => 'crvs.module.ci::servers.write',
'crvs.module.ci::servers.delete' => 'crvs.module.ci::servers.delete',
'crvs.module.ci::keys.read' => 'crvs.module.ci::keys.read',
'crvs.module.ci::keys.write' => 'crvs.module.ci::keys.write',
'crvs.module.ci::keys.delete' => 'crvs.module.ci::keys.delete',
'crvs.module.ci::vcs.read' => 'crvs.module.ci::vcs.read',
'crvs.module.ci::vcs.write' => 'crvs.module.ci::vcs.write',
'crvs.module.ci::vcs.delete' => 'crvs.module.ci::vcs.delete',
'crvs.module.ci::teams.read' => 'crvs.module.ci::teams.read',
'crvs.module.ci::teams.write' => 'crvs.module.ci::teams.write',
'crvs.module.ci::teams.delete' => 'crvs.module.ci::teams.delete',
'crvs.module.ci::credentials.read' => 'crvs.module.ci::credentials.read',
'crvs.module.ci::credentials.write' => 'crvs.module.ci::credentials.write',
'crvs.module.ci::credentials.delete' => 'crvs.module.ci::credentials.delete',
        ]
    }
}